import React, { useMemo, useState } from 'react';
import { Activity, AlertTriangle, Bell, ClipboardList, Database, Home, Package, Plus, Trash2 } from 'lucide-react';
import { useRahatStore, useCurrentUser } from '../../store/useRahatStore';
import { EMERGENCY_TYPES, RESOURCE_CATEGORIES, SEVERITIES, INCIDENT_TYPES } from '../../constants/rahat';
import type { EmergencyRequest } from '../../types/rahat';

interface OperationsPageProps { section: 'requests' | 'resources' | 'incidents' | 'shelters' | 'analytics' | 'notifications' | 'audit'; }
const labels = { requests: 'Requests', resources: 'Resources', incidents: 'Incidents', shelters: 'Shelters', analytics: 'Analytics', notifications: 'Notifications', audit: 'Audit log' };

const OperationsPage: React.FC<OperationsPageProps> = ({ section }) => {
  const requests = useRahatStore((s) => s.requests); const resources = useRahatStore((s) => s.resources); const incidents = useRahatStore((s) => s.incidents); const shelters = useRahatStore((s) => s.shelters); const notifications = useRahatStore((s) => s.notifications); const auditLog = useRahatStore((s) => s.auditLog); const volunteers = useRahatStore((s) => s.volunteers);
  const currentUser = useCurrentUser(); const deleteRequest = useRahatStore((s) => s.deleteRequest); const createResource = useRahatStore((s) => s.createResource); const createIncident = useRahatStore((s) => s.createIncident); const createShelter = useRahatStore((s) => s.createShelter);
  const [notice, setNotice] = useState('');
  const activeRequests = requests.filter((request) => !['RESOLVED', 'CANCELLED', 'DELIVERED'].includes(request.status));
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (section === 'resources') createResource({ name: String(data.get('name')), category: String(data.get('category')) as never, quantity: Number(data.get('quantity')), unit: String(data.get('unit')), storageLocation: String(data.get('storageLocation')), lowThreshold: Number(data.get('lowThreshold')) }); if (section === 'incidents') createIncident({ name: String(data.get('name')), type: String(data.get('type')) as never, affectedArea: String(data.get('affectedArea')), severity: String(data.get('severity')) as never, description: String(data.get('description')), status: 'Active' }); if (section === 'shelters') createShelter({ name: String(data.get('name')), address: String(data.get('address')), capacity: Number(data.get('capacity')), location: { lat: Number(data.get('lat')), lng: Number(data.get('lng')), address: String(data.get('address')) }, foodAvailable: data.get('food') === 'on', waterAvailable: data.get('water') === 'on', medicalAvailable: data.get('medical') === 'on', status: 'Open' }); setNotice(`${labels[section]} record created.`); event.currentTarget.reset(); };
  const icon = { requests: ClipboardList, resources: Package, incidents: AlertTriangle, shelters: Home, analytics: Activity, notifications: Bell, audit: Database }[section]; const Icon = icon;
  return <div className="space-y-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-blue-600">Operations</p><h1 className="mt-1 text-2xl font-bold text-slate-900">{labels[section]}</h1><p className="mt-1 text-sm text-slate-500">Live workspace data, refreshed automatically.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500" />Live · refresh 3s</span></div>{notice && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}{section === 'analytics' ? <Analytics requests={requests} volunteers={volunteers} resources={resources} shelters={shelters} /> : section === 'notifications' ? <List title="Notifications" icon={Icon} items={notifications.map((item) => `${item.title}: ${item.message}`)} empty="No notifications yet." /> : section === 'audit' ? <List title="Audit trail" icon={Icon} items={auditLog.map((item) => `${item.action} · ${item.entityType} · ${new Date(item.timestamp).toLocaleString()}`)} empty="No audit events yet." /> : section === 'requests' ? <RequestList requests={requests} currentUser={currentUser} deleteRequest={deleteRequest} /> : <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><CreateForm section={section} submit={submit} />{section === 'resources' ? <List title="Inventory" icon={Icon} items={resources.map((item) => `${item.name} · ${item.quantity} ${item.unit} · ${item.storageLocation}`)} empty="No resources created." /> : section === 'incidents' ? <List title="Active incidents" icon={Icon} items={incidents.map((item) => `${item.name} · ${item.status} · ${item.severity}`)} empty="No incidents created." /> : <List title="Shelters" icon={Icon} items={shelters.map((item) => `${item.name} · ${item.occupied}/${item.capacity} occupied · ${item.status}`)} empty="No shelters created." />}</div>}</div>;
};

const CreateForm: React.FC<{ section: OperationsPageProps['section']; submit: (event: React.FormEvent<HTMLFormElement>) => void }> = ({ section, submit }) => <form onSubmit={submit} className="space-y-4 rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2 font-semibold text-slate-900"><Plus className="h-4 w-4 text-blue-600" />Create {section.slice(0, -1)}</div><Field label="Name" name="name" required />{section === 'resources' && <><Select label="Category" name="category" options={RESOURCE_CATEGORIES} /><Field label="Quantity" name="quantity" type="number" required /><Field label="Unit" name="unit" defaultValue="unit" required /><Field label="Storage location" name="storageLocation" required /><Field label="Low threshold" name="lowThreshold" type="number" defaultValue="10" required /></>}{section === 'incidents' && <><Select label="Type" name="type" options={INCIDENT_TYPES} /><Select label="Severity" name="severity" options={SEVERITIES} /><Field label="Affected area" name="affectedArea" required /><label className="block text-sm font-medium text-slate-700">Description<textarea name="description" required rows={3} className="mt-1 w-full rounded-lg border border-slate-300 p-2" /></label></>}{section === 'shelters' && <><Field label="Address" name="address" required /><Field label="Capacity" name="capacity" type="number" required /><div className="grid grid-cols-2 gap-2"><Field label="Latitude" name="lat" type="number" step="any" defaultValue="26.98" required /><Field label="Longitude" name="lng" type="number" step="any" defaultValue="84.5" required /></div><div className="flex gap-3 text-xs"><label><input type="checkbox" name="food" /> Food</label><label><input type="checkbox" name="water" /> Water</label><label><input type="checkbox" name="medical" /> Medical</label></div></>}<button className="w-full rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Create record</button></form>;
const Field: React.FC<React.InputHTMLAttributes<HTMLInputElement> & { label: string }> = ({ label, ...props }) => <label className="block text-sm font-medium text-slate-700">{label}<input {...props} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5" /></label>;
const Select: React.FC<{ label: string; name: string; options: readonly string[] }> = ({ label, name, options }) => <label className="block text-sm font-medium text-slate-700">{label}<select name={name} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5">{options.map((option) => <option key={option}>{option}</option>)}</select></label>;
const List: React.FC<{ title: string; icon: React.ComponentType<{ className?: string }>; items: string[]; empty: string }> = ({ title, icon: Icon, items, empty }) => <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="flex items-center gap-2 font-semibold text-slate-900"><Icon className="h-4 w-4 text-blue-600" />{title}</h2><div className="mt-4 space-y-2">{items.length ? items.map((item, index) => <div key={`${item}-${index}`} className="rounded-lg border border-slate-100 bg-slate-50 p-3 text-sm text-slate-700">{item}</div>) : <p className="text-sm text-slate-500">{empty}</p>}</div></section>;
const RequestList: React.FC<{ requests: EmergencyRequest[]; currentUser: ReturnType<typeof useCurrentUser>; deleteRequest: (id: string, ctx: { actorId: string | null; actorName: string; role?: 'coordinator' }) => { ok: boolean } }> = ({ requests, currentUser, deleteRequest }) => <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">All requests</h2><div className="mt-4 space-y-2">{requests.length ? requests.map((request) => <div key={request.id} className="flex items-center justify-between gap-3 rounded-lg border border-slate-100 p-3"><div><p className="font-mono text-sm font-semibold">{request.id}</p><p className="text-sm text-slate-600">{request.emergencyType} · {request.status} · {request.citizenName}</p></div><button type="button" onClick={() => { if (window.confirm(`Delete ${request.id}?`) && currentUser) deleteRequest(request.id, { actorId: currentUser.id, actorName: currentUser.name, role: 'coordinator' }); }} className="inline-flex items-center gap-1 rounded-md border border-red-200 px-2.5 py-1.5 text-xs font-semibold text-red-700 hover:bg-red-50"><Trash2 className="h-3.5 w-3.5" />Delete</button></div>) : <p className="text-sm text-slate-500">No requests yet.</p>}</div></section>;
const Analytics: React.FC<{ requests: EmergencyRequest[]; volunteers: ReturnType<typeof useRahatStore.getState>['volunteers']; resources: ReturnType<typeof useRahatStore.getState>['resources']; shelters: ReturnType<typeof useRahatStore.getState>['shelters'] }> = ({ requests, volunteers, resources, shelters }) => <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Active requests', requests.filter((item) => !['RESOLVED', 'CANCELLED', 'DELIVERED'].includes(item.status)).length], ['Volunteers', volunteers.length], ['Resources', resources.length], ['Shelter capacity', shelters.reduce((total, shelter) => total + shelter.capacity, 0)]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value}</p></div>)}</div>;
export default OperationsPage;
